# Generated by Django 5.2.4 on 2025-07-28 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
