# Generated by Django 5.2.4 on 2025-07-29 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_blog_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='blog-video'),
        ),
    ]
